### PR TITLE
Add torrent name to description

### PR DESCRIPTION
**Pull request by ragmehos**
Add torrent name to description as it helps figure out more information about the link, for e.g, in the image below, it was an audio launch but it's not easy to understand without the torrent name. 
Screenshot 2024-01-28 at 8 41 50 AM

After this change, it looks like this : 
Screenshot 2024-01-28 at 8 30 28 AM

### CODE REVIEW

**Comment by mhdzumair** [comment]
Isn't this too detail to view? Specially on TV?

**Comment by mhdzumair** [comment]
> Isn't this too detail to view? Specially on TV?

I like the more detail that we can provide but the torrent name is having unnecessary things.

**Comment by ragmehos** [comment]
Maybe we can do something like torrentio and move the quality info to the left bar and have the name on the right and combine a few sections?

Screenshot 2024-01-28 at 10 22 23 AM

For tamilmv and blasters streams, its maybe ok, but for torrentio as well as prowlarr, searching for something like fight club shows both the english and tamil ones and to distinguish, we need to provide the name for people to figure out what they want.

**Comment by mhdzumair** [comment]
Let's make this as configurable through config page. And default is not adding the torrent name. How about that?

**Comment by ragmehos** [comment]
> Let's make this as configurable through config page. And default is not adding the torrent name. How about that?

Sounds reasonable.

**Comment by mhdzumair** [comment]
Are you going to do the implementation as configurable?

**Pull request closed without merging**
