### PR TITLE
Create 1337x.py

### PR DESCRIPTION
**Pull request by Nexus-Gits**
Please check and update if needed for 1337x torrent scrapper

### CODE REVIEW

**Comment by mhdzumair** [comment]
Hi @Nexus-Gits thank you for your contribution. However, the script doesn't scrape and storing the data into database. Please see the [tamilmv](https://github.com/mhdzumair/MediaFusion/blob/develop/scrappers/tamilmv.py) and [tamil_blasters](https://github.com/mhdzumair/MediaFusion/blob/develop/scrappers/tamil_blasters.py) scraping script. 

Also update the pull request target branch to develop instead of main.

**Comment by Nexus-Gits** [comment]
ok. thank you for your reply and grat work

**Comment by mhdzumair** [comment]
I appreciate your contribution. Hope you will do the great contribution in the future.

**Comment by mhdzumair** [comment]
You can follow the guideline in README about setting up the addon in your local. so that way you can make sure everything is working and the scrap data is saved in the db.

**Pull request closed without merging**
